version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          

      - run:
          name: Create test directory
          command: |
            mkdir -p ./results/nosetests
            
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            nosetests -v --with-xunit --xunit-file ./results/nosetests/results.xml
          
      - store_test_results:
          path: ./results/
